### ISSUE TITLE
Q/REQ: Trigger scheduled task manually or run an SSH command

### ISSUE THREAD

**Issue by quadcom** [vletroye/Mods#19]
Hey there, awesome work!

I'm trying to figure out how I would go about triggering a scheduled task or running the script that the task calls?

I use Filebot and instead of scheduling its run, I want to run it manually on demand. The problem is I have to go into the scheduled tasks area each time to run it. I am looking for a way to have a shortcut, either on the desktop or taskbar that I can hit to fire the script.

Can this be done with your app builder?

**Comment by quadcom** [comment]
Trying to get init 3rdparty installed via the CPHub community and I get an error. The current version available is 1.9-003.

```
Failed to install "init 3rdparty"

Please install and run at least one PHP version via the package center before installing this package.
```

I've installed PHP7.4 and 7.3. Both are running according to Package Center. Not sure what else to do from here.

Any ideas?

**Comment by vletroye** [comment]
You should do a package with MODS to run a bash command. The same command as scheduled via the Task Scheduler.
I am also using filebot, so it should be something like: /usr/local/filebot-node/task 1

Regarding "init 3rdparty", are you using nginx or apache as default web server ?

**Comment by vletroye** [comment]
I did create a sample "MODS Filebot Runner" that you can download from [here](https://github.com/vletroye/SynoPackages/tree/master/MODS%20Filebot%20Runner)

It's executing  /usr/local/filebot-node/task 1 without dependency on "init 3rdparty" and apache.
Instead, it's depending on nginx and the trick explained [here ](https://github.com/vletroye/SynoPackages/wiki/MODS-Sample---Simple-Cgi) to redirect all calls via a kind of "proxy cgi".

NB.: as filebot takes quite some time to start, wait long enough to see the output ;)
I didn't succeed to force a flush line by line of the stdout buffer 
And you will have to cleanup on the various installation scripts, etc...

![image](https://user-images.githubusercontent.com/9768028/104092542-e66d1000-5284-11eb-8f6f-184f953c04cd.png)

**Comment by quadcom** [comment]
Thanks very much, vletroye, now being a total noob I need to wrap my head around this. 

As far as Apache or NGINX, aside from the Synology UI I'm not running any webserver at all meaning, I don't have any websites being hosted on the box. Not sure if this is what you mean. If it were possible to modify the server driving the Synology UI to use NGINX I had no idea that was even possible.

As it stands I couldn't get init 3rdparty installed due to this dependency that I couldn't solve. Could it be that I need to install Apache/NGINX packages with PHP even though I host no sites? Are there security concerns by doing that?

**Comment by vletroye** [comment]
The "init 3rdparty" will only work if you installed the "Web Station".

But the new package that I created for you "MODS Filebot Runner" **does not require the "Web Station"** (and hence, not need for init 3rd Party). Alos, nginx is installed by default within DSM nowadays...

Be sure to use [this SPK ](https://github.com/vletroye/SynoPackages/blob/master/MODS%20Filebot%20Runner/MODS_Filebot_Runner.spk)

**Comment by quadcom** [comment]
Hey vletroye, I seem to be stuck. So I DL'd the spk and did a manual install on the DS. Everything installed after I got PHP installed but I couldn't figure out what to do after that.

There wasn't anything new in the app drawer and I couldn't see anything in the SPK that I could edit to set which script is run nor could I determine how the shortcut is placed on the desktop.

My apologies for being the noob here. I know enough to break things pretty good.

**Comment by vletroye** [comment]
Hi 

First, double check that FileBot Runner is well installed within the Package Center 

![image](https://user-images.githubusercontent.com/9768028/104811125-af08e100-57f9-11eb-9d07-e6fb8edac066.png)

Regarding the configuration of the task to be run, you must edit the file mods.sh in the SPK (with MODS) **before** installing it!
You can also edit that file after installation via a SSH console. I recommend the text editor 'Nano' instead of vi if you are not comfortable with linux ?! Nano is a package that can be installed via the Community

![image](https://user-images.githubusercontent.com/9768028/104811201-5128c900-57fa-11eb-987b-32dabdfb7c52.png)

To edit the file mods.sh via SSH, type:
> nano /var/packages/MODS_Filebot_Runner/target/ui/mods.sh

You can also test that it works fine, still via SSH, typing:
> sh /var/packages/MODS_Filebot_Runner/target/ui/mods.sh


Once the package properly installed, you should have this new icon in the main DSM menu:

![image](https://user-images.githubusercontent.com/9768028/104810998-c7c4c700-57f8-11eb-85b4-53c352139a57.png)

If you don't see it, refresh the page with CTRL-F5 in your browser (re-login into DSM).
If you still don't see the icon, clear the cache of your browser and than CTRL-F5 again.

Kind regards,

V.

**Comment by quadcom** [comment]
Hmmm, real head-scratcher here. I installed Mods on my laptop and DL'd the Filebot Runner Package. I opened the folder that the Filebot Runner was in and manually edited the mods.sh file in Notepad++ to run the correct SSH script. I then ran the package/build and manually installed the SPK from that folder into the DSM. It installed without any errors and it says it's running but again, there's no icon in the app drawer.

I've logged out and back in. I've cleared the cache in Chrome but still no sign of it anywhere.

![image](https://user-images.githubusercontent.com/7085931/104823489-6280ce00-5818-11eb-9e41-605cdebab565.png)


I checked the SH file with nano and it is configured correctly.
![image](https://user-images.githubusercontent.com/7085931/104823645-b344f680-5819-11eb-99ec-08434d3acecb.png)

I just can't see the icon in the drawer??

**Comment by vletroye** [comment]
You are not the first user reporting issues with the icons. But I never understood the reason for such issues...
It could be that a previous version of the package failed to install and DSM keeps some memory of it ?!

Could you uninstall the package and then try this new version:
https://www.beatificabytes.be/sspks/packages/MODS_Filebot_Runner_2.spk

I did change the name of the package so it won't be impacted by any previous versions.
NB.: it is published (and so signed) on my Package Server : https://www.beatificabytes.be/sspks/

PS.: By the way, which build version of DSM do you have ?

**Comment by quadcom** [comment]
Hmmm, plot thickens. I DL'd the new SPK v2 you made, removed the installed one and installed the new.

All installed fine and it is running. I haven't checked the mods.sh yet. 

Still no icon in the drawer??

My DSM version:
![image](https://user-images.githubusercontent.com/7085931/104824379-20a75600-581f-11eb-81fe-8970f7b245dd.png)

**Comment by vletroye** [comment]
Ok, very same version as mine... That's not the pblm.

Do you have an adblocker? I saw once that it was the root cause for one user.
Did you try with another browser: Edge or Internet Explorer ?

If you install another package, do you see the icon ?
- Any one from the syno community 
- This web console, from my Package Server: https://www.beatificabytes.be/sspks/packages/MODS_WebConsole.spk

**Comment by quadcom** [comment]
Figure it out!

Permissions!

By default no-one has permission to access the application. Giving everyone access allowed the icon to be shown in the drawer.

![image](https://user-images.githubusercontent.com/7085931/104824535-8b0cc600-5820-11eb-9c2c-adca5f3cbfb5.png)

**Comment by quadcom** [comment]
LOL, one problem down, new problem arises. I edited the sh file with nano and confirmed the script path is correct.

![image](https://user-images.githubusercontent.com/7085931/104824690-01f68e80-5822-11eb-90aa-790b80817dc1.png)

Got a new error message


![image](https://user-images.githubusercontent.com/7085931/104824629-77159400-5821-11eb-94b0-819b57720c2c.png)

**Comment by vletroye** [comment]
This is because the php page does not run. Open the page in a new window.
![image](https://user-images.githubusercontent.com/9768028/104824703-6894a000-5854-11eb-9d76-64f2e4861379.png)

Then look at the error with the Chrome Debugger. I guess that the redirection created for nginx is not working for you...

**Comment by quadcom** [comment]
mods.php returning a 404

![image](https://user-images.githubusercontent.com/7085931/104824737-834e2100-5822-11eb-9858-f9252070b798.png)

**Comment by vletroye** [comment]
Can you run this:  
cd /var/packages/MODS_Filebot_Runner/target/ui/
php mods.php

**Comment by vletroye** [comment]
In order to run php pages stored in such folder, I create a config for nginx:  dsm.cgi.conf
This config is linked into the folder /usr/syno/share/nginx/conf.d/

Try: ls -l /usr/syno/share/nginx/conf.d/
Do you see something like: dsm.MOD_Filebot_Run.conf -> /volume1/@appstore/MOD_Filebot_Run/ui/dsm.cgi.conf

If you do, it means that nginx didn't take that file into account...

Try to restart nginx: sudo synoservice --restart nginx

**Comment by quadcom** [comment]
![image](https://user-images.githubusercontent.com/7085931/104825032-40417d00-5825-11eb-8dc7-33b1366e117d.png)


Yours - dsm.MOD_Filebot_Run.conf -> /volume1/@appstore/MOD_Filebot_Run/ui/dsm.cgi.conf
Mine - dsm.MODS_Filebot_Runner_2.conf -> /volume1/@appstore/MODS_Filebot_Runner_2/ui/dsm.cgi.conf


Slight differences there. Could this be the problem??

Restarted NGINX and still no go.

I ran HTOP in another putty and watched NGINX restart. I then hard reloaded DSM UI and opened the FB shortcut in a new window. Same response as before. mods.php returns a 404.

![image](https://user-images.githubusercontent.com/7085931/104827192-4b96a780-5829-11eb-8210-eed74b77a655.png)

PS. I should add that WebConsole works fine. Link opens right in the DSM UI


EDT: I just noticed it's trying to open 

/webman/3rdparty/**MODS_Filebot_Runner**/mods.php 

not 

/webman/3rdparty/**MODS_Filebot_Runner_2**/mods.php

**Comment by quadcom** [comment]
I think if I remove v2 and install the original one, configure the SH file and ensure the app permissions are correct it should be fine.

I'll let you know.



EDIT: SUCCESS!!!!!

**Comment by vletroye** [comment]
Ok, great !!! 
And sorry, I probably did a mistake somewhere in my version 2...
